version: '3'
services:
  api:
    build: 
      dockerfile: ./docker/api.Dockerfile
      context: .
    ports:
      - "3333:3333"

  interface:
    build:
      dockerfile: ./docker/interface.Dockerfile
      context: .
    ports:
      - "3000:3000"